language: php
php:
  - 5.4

service: postgresql


install:
    - sudo pip install -r requirements.txt --use-mirrors

before_script:
  - sudo ./setup_fpm_and_nginx_for_travis.sh

script: ./curl_hello.sh
